### ISSUE TITLE
As a buyer, I want to be able to contact sellers of items I'm interested in to ask questions about the item, set up times to meet and discuss payment.

### ISSUE THREAD

**Issue by Aosaliu** [cse442-spring-2020-offering/cse442-semester-project-talking-apple-juice#1]
### Acceptance Test
- Open Application
- Input username and password
- Click on a new product
- Click on 'Contact Seller'
- Write a message and click 'Send'
(As a buyer, you can currently only see the message in the message history if you are responded to)

- Log in as the user selling the product
- Check messages, you should see the username and be able to open it.

**Comment by sultanol97** [comment]
Empty messages shouldn't be able to be sent.
Also , protect the message input from running scripts

**Comment by bluejaytea** [comment]
Shouldnt be able to message yourself
Add the item you contact the seller from into the message body
