### ISSUE TITLE
Create Settings dropdown option

### ISSUE THREAD

**Issue by horepoh** [cse442-spring-2020-offering/cse442-semester-project-talking-apple-juice#16]
Acceptance Test:
1. Open the app
2. Press the 'Enter' button
3. Press the 3-dot line on the top right
4. Press 'Settings'
5. You can view a basic settings page which features a switch

**Comment by bluejaytea** [comment]
Acceptance Test:
1. Open the app
2. Press the 'Enter' button
3. Press the 3-dot menu on the top right
4. Press 'Settings'
5. You can view a basic settings page which features a switch
