### ISSUE TITLE
Create a Back Button on menu bar

### ISSUE THREAD

**Issue by horepoh** [cse442-spring-2020-offering/cse442-semester-project-talking-apple-juice#17]
**Task Test:**
1. Open the app
2. Press the 'Enter' button
3. Press the 3-dot line on the top right
4. Press any of the buttons to go to a new page
5. Press the arrow button on the top left of the page to return to the home menu

**Comment by bluejaytea** [comment]
Acceptance Test:
1. Open the app
2. Press the 'Enter' button
3. Press the 3-dot menu on the top right
4. Press any of the buttons to go to a new page
5. Press the arrow button on the top left of the page to return to the home menu
