### ISSUE TITLE
Create Account dropdown option

### ISSUE THREAD

**Issue by horepoh** [cse442-spring-2020-offering/cse442-semester-project-talking-apple-juice#18]
**Task Test:**
1. Open the app
2. Press the 'Enter' button
3. Press the 3-dot line on the top right
4. Press 'Account'
5. You can view your page and enter information in any of the text boxes (All 'Confirm' does is clear the new password entries at the moment)

**Comment by bluejaytea** [comment]
Acceptance Test:
1. Open the app
2. Press the 'Enter' button
3. Press the 3-dot menu on the top right
4. Press 'Account'
5. You can view your page and enter information in any of the text boxes (All 'Confirm' does is clear the new password entries at the moment)
