### ISSUE TITLE
As a buyer or seller, I want to be able to have a menu bar, so that I can navigate to my account/profile page,,transaction history, messages,  settings or new sales.

### ISSUE THREAD

**Issue by horepoh** [cse442-spring-2020-offering/cse442-semester-project-talking-apple-juice#19]
**Acceptance Test:**
1. Open the app
2. Look for text box labeled "Username"
3. Input username
4. Look for text box labeled "Password"
5. Input password
6. Press "Enter" to access account and enter the homepage.
7. Look to the top of the screen for titled menu bar

**Comment by Aosaliu** [comment]
Acceptance Test:
1. Open the app
2. Look for text box labeled "Username"
3. Input username
4. Look for text box labeled "Password"
5. Input password
6. Press "Enter" to access account and enter the homepage.
7. Look to the top of the screen for the dotted line
8. Press dotted line and a dropdown menu should appear
