### ISSUE TITLE
As a buyer , I would like the option to leave reviews on the seller so that I may inform others of legitimacy

### ISSUE THREAD

**Issue by horepoh** [cse442-spring-2020-offering/cse442-semester-project-talking-apple-juice#20]
### Acceptance Test
1. Open Application
2. Enter Account information (Username and Password)
3. Click enter 
4. Once on homepage, click on a product
5. Click on seller name
6. Click "Rate as Seller"
7. Input a review for seller
8. Input a whole number rating
9. Click  "Submit Review" button (Note: must also input a ratings, for the review to be submitted successfully)

**Comment by sultanol97** [comment]
Adjust functionality to only allow reviews from users other than you.
