### ISSUE TITLE
Create New Sales dropdown option

### ISSUE THREAD

**Issue by horepoh** [cse442-spring-2020-offering/cse442-semester-project-talking-apple-juice#23]
**Task Test:**
1. Open the app
2. Press the 'Enter' button
3. Press the 3-dot menu on the top right
4. Press 'New Sale'
5. Enter text into the description area, price area, and length of bid area.

**Comment by bluejaytea** [comment]
Acceptance Test:
1. Open the app
2. Press the 'Enter' button
3. Press the 3-dot menu on the top right
4. Press 'New Sale'
5. Enter text into the description area, price area, and length of bid area.
