### ISSUE TITLE
As a seller,  I  want to see past sales on an item so that I can see the potential value of my product.

### ISSUE THREAD

**Issue by Aosaliu** [cse442-spring-2020-offering/cse442-semester-project-talking-apple-juice#8]
### Acceptance Test
1. Open Application
2. Enter Account information (Username and Password)
3. Click enter 
4. Once on homepage, click on a 3-dot menu
5. Click "Transactions"
6.  Past sales should be displayed 
(Note: at then moment only the name of the product is displayed)

**Comment by sultanol97** [comment]
Only allow correct user to change the item as sold, so that the correct items are listed under sold items.
