### ISSUE TITLE
As a buyer, I want to be able to leave ratings on seller so that I can let other potential buyers know if the seller is legit or not.

### ISSUE THREAD

**Issue by Aosaliu** [cse442-spring-2020-offering/cse442-semester-project-talking-apple-juice#97]
### Acceptance Test
1. Open Application
2. Enter Account information (Username and Password)
3. Click enter 
4. Once on homepage, click on a product
5. Click on seller name
6. Click "Rate as Seller"
7. Input a whole number rating for seller 
8. Input a review for other users to see
9. Click  "Submit Review" button

**Comment by sultanol97** [comment]
Fix the functionality so that you are not allowed to review yourself. So only others are allowed to review you.
